### ISSUE TITLE
Brennenstuhl compatibility

### ISSUE THREAD

**Issue by Depechie** [d-Rickyy-b/pyBrematic#28]
Is there any info on what other Brennenstuhl devices are compatible with this library? Do all Brennenstuhl devices use the same technology?

In my case I'm wondering about the https://www.brennenstuhl.be/nl-BE/producten/smart-home/brennenstuhl-r-connect-wifi-stekkerdoos-wa-3000-xs02-zwart-ip44-fr

**Comment by d-Rickyy-b** [comment]
Hi there, I am not sure if you closed the issue because you found out or if it was by mistake. Either way I guess it's always good to document the information for other folks who may stumble across this repo/issue.

The Brennenstuhl plug you posted uses wifi instead of the 433 MHz band. This module sends specific UDP packets to a 433 MHz gateway so that this gateway can send out the 433 MHz signal to the plug. I very much assume that the plug you requested wouldn't be compatible with this library since it seems to be connected via wifi only.

**Comment by Depechie** [comment]
Yeah after I posted the message I noticed the difference in models too... hence why I closed the issue again ;)
